version: '3'

services:

  db:
    image: postgres:14.3-alpine
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'

  app:
    build: .
    tty: true
    command: sh -c "python manage.py makemigrations && python manage.py migrate && DJANGO_SUPERUSER_PASSWORD=admin python manage.py createsuperuser --username=admin --email=admin@example.com --noinput && python manage.py create_test_data && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8001:8000'
    #      ссылка сайта на http://localhost:8001/
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pg_data: